name: customs-broker-portal
services:
- name: backend
  git:
    repo_clone_url: https://github.com/Oakhampton1111/customsportal.git
    branch: master
  source_dir: backend
  dockerfile_path: Dockerfile
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: ENVIRONMENT
    value: production
  - key: ANTHROPIC_API_KEY
    value: ${ANTHROPIC_API_KEY}
    type: SECRET
  - key: SECRET_KEY
    value: ${SECRET_KEY}
    type: SECRET
  - key: CORS_ORIGINS
    value: https://customs-broker-portal.ondigitalocean.app
  health_check:
    http_path: /health
  http_port: 8000
  routes:
  - path: /api
  - path: /docs
  - path: /health

- name: frontend
  git:
    repo_clone_url: https://github.com/Oakhampton1111/customsportal.git
    branch: master
  source_dir: frontend
  dockerfile_path: Dockerfile
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: VITE_API_URL
    value: https://customs-broker-portal.ondigitalocean.app
  - key: VITE_ENVIRONMENT
    value: production
  http_port: 8080
  routes:
  - path: /

databases:
- name: db
  engine: PG
  version: "15"
  size: basic-xs
  num_nodes: 1
